Toma\TestBundle\Entity\Article:
  type: entity
  table: article
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      unique: true